/**************************
BORRADO DE LA TABLA Control ficha Verificacion Detallado Pendientes por Trabajar
REP_CON_VERIF_IN_PROC_WORK_DET
******************************/

SET SERVEROUTPUT ON
DECLARE tbl_exist  PLS_INTEGER;

BEGIN

select count(*) into tbl_exist from all_tables where table_name = 'REP_CON_VERIF_IN_PROC_WORK_DET';
if tbl_exist = 1 then
    execute immediate 'drop table REPORTADMIN.REP_CON_VERIF_IN_PROC_WORK_DET';
end if;

END;
/
/****************************
CREADO DE LA TABLA Control fichas Verificacion Detallado Pendientes Trabajadas
*****************************/

CREATE TABLE "REPORTADMIN"."REP_CON_VERIF_IN_PROC_WORK_DET" 
   (	
    "ID_CON_VERIF_REPORT" NUMBER(20,0) NOT NULL ENABLE,     
    "REGISTER_DATE" DATE,
    "LAST_REQUEST_ID"   NUMBER(*,0),
    "ACTIVE" NUMBER(1,0),
	"CREATION_DATE" DATE , 
	"MODIFICATION_DATE" DATE, 
	 CONSTRAINT "REP_CN_VERIF_IN_FK" PRIMARY KEY ("ID_CON_VERIF_REPORT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_REPORT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_REPORT" ;
  
COMMENT ON TABLE "REPORTADMIN"."REP_CON_VERIF_IN_PROC_WORK_DET" is 'Tabla que controla la ejecución del Job , que trae las fichas en verificaicon pendientes por  trabajadas';
COMMENT ON COLUMN "REPORTADMIN"."REP_CON_VERIF_IN_PROC_WORK_DET"."ID_CON_VERIF_REPORT" IS 'Id tabla Control.';
COMMENT ON COLUMN "REPORTADMIN"."REP_CON_VERIF_IN_PROC_WORK_DET"."REGISTER_DATE" IS 'Fecha de Ejecución Job';
COMMENT ON COLUMN "REPORTADMIN"."REP_CON_VERIF_IN_PROC_WORK_DET"."LAST_REQUEST_ID" IS 'Id del ultimo registro request_Id de WFLNGADMIN.WFL_REQUEST';
COMMENT ON COLUMN "REPORTADMIN"."REP_CON_VERIF_IN_PROC_WORK_DET"."ACTIVE" IS 'Registro Activo 1:True 0:False';
COMMENT ON COLUMN "REPORTADMIN"."REP_CON_VERIF_IN_PROC_WORK_DET"."CREATION_DATE" IS 'Fecha de creación del registro';
COMMENT ON COLUMN "REPORTADMIN"."REP_CON_VERIF_IN_PROC_WORK_DET"."MODIFICATION_DATE" IS 'Fecha modificacion del registro';