//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 02:06:27 PM COT 
//


package com.parameta.jgr.soapService.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.parameta.jgr.soapService.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EmpleadoResponse_QNAME = new QName("http://www.example.org/Empleado", "empleadoResponse");
    private final static QName _EmpleadoRequest_QNAME = new QName("http://www.example.org/Empleado", "empleadoRequest");
    private final static QName _EmpleadoFault_QNAME = new QName("http://www.example.org/Empleado", "empleadoFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.parameta.jgr.soapService.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmpleadoRequest }
     * 
     */
    public EmpleadoRequest createEmpleadoRequest() {
        return new EmpleadoRequest();
    }

    /**
     * Create an instance of {@link EmpleadoResponse }
     * 
     */
    public EmpleadoResponse createEmpleadoResponse() {
        return new EmpleadoResponse();
    }

    /**
     * Create an instance of {@link EmpleadoFault }
     * 
     */
    public EmpleadoFault createEmpleadoFault() {
        return new EmpleadoFault();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmpleadoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Empleado", name = "empleadoResponse")
    public JAXBElement<EmpleadoResponse> createEmpleadoResponse(EmpleadoResponse value) {
        return new JAXBElement<EmpleadoResponse>(_EmpleadoResponse_QNAME, EmpleadoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmpleadoRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Empleado", name = "empleadoRequest")
    public JAXBElement<EmpleadoRequest> createEmpleadoRequest(EmpleadoRequest value) {
        return new JAXBElement<EmpleadoRequest>(_EmpleadoRequest_QNAME, EmpleadoRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmpleadoFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Empleado", name = "empleadoFault")
    public JAXBElement<EmpleadoFault> createEmpleadoFault(EmpleadoFault value) {
        return new JAXBElement<EmpleadoFault>(_EmpleadoFault_QNAME, EmpleadoFault.class, null, value);
    }

}
